#!/bin/bash

export WINEPREFIX="$HOME/.winbox/wine"
export WINEDLLOVERRIDES="mscoree=;winegstreamer="
export WINEDEBUG=-all

DUDE_HOME="$HOME/.winbox/dude"

if [ ! -d "$WINEPREFIX" ]; then
    mkdir -p "$WINEPREFIX"
    wineboot -u
fi

if [ ! -d "$DUDE_HOME" ]; then
    mkdir -p "$DUDE_HOME"
fi

find /usr/share/thedude -type f -exec ln -sf {} "$DUDE_HOME/" \;

if [ -h "$DUDE_HOME/data" ]; then
    rm -f "$DUDE_HOME/data"
fi

cd "$DUDE_HOME" || exit 1
exec wine "$DUDE_HOME/dude.exe" "$@"
